"""add tables for terms of service and signatures

Revision ID: 44ec522465e5
Revises: 
Create Date: 2021-10-07 15:12:14.309053

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '44ec522465e5'
down_revision = None
branch_labels = ('quetz-tos',)
depends_on = 'quetz'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'quetz_tos',
        sa.Column('id', sa.LargeBinary(length=16), nullable=False),
        sa.Column('uploader_id', sa.LargeBinary(length=16), nullable=True),
        sa.Column('filename', sa.String(), nullable=True),
        sa.Column(
            'time_created',
            sa.DateTime(),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'quetz_tos_signatures',
        sa.Column('tos_id', sa.LargeBinary(length=16), nullable=False),
        sa.Column('user_id', sa.LargeBinary(length=16), nullable=False),
        sa.Column(
            'time_created',
            sa.DateTime(),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['tos_id'],
            ['quetz_tos.id'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('tos_id', 'user_id'),
        sa.UniqueConstraint('tos_id', 'user_id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quetz_tos_signatures')
    op.drop_table('quetz_tos')
    # ### end Alembic commands ###
