"""initial revision

Revision ID: b8b107f2c752
Revises: a80fb051a659
Create Date: 2020-11-25 10:30:37.716199

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b8b107f2c752'
down_revision = 'a80fb051a659'
branch_labels = ('quetz-conda_suggest',)
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'quetz_conda_suggest_metadata',
        sa.Column('version_id', sa.LargeBinary(length=16), nullable=False),
        sa.Column('data', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ['version_id'],
            ['package_versions.id'],
        ),
        sa.PrimaryKeyConstraint('version_id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quetz_conda_suggest_metadata')
    # ### end Alembic commands ###
