"""add task pending state

Revision ID: 30241b33d849
Revises: 303ff70c27fc
Create Date: 2021-01-07 14:39:43.251123

"""
# import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '30241b33d849'
down_revision = '303ff70c27fc'
branch_labels = None
depends_on = None


def upgrade():
    # manually entered
    # https://alembic.sqlalchemy.org/en/latest/api/runtime.html#alembic.runtime.migration.MigrationContext.autocommit_block
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE taskstatus  ADD VALUE 'created'")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
