"""add channel metadata

Revision ID: 546854af251f
Revises: ea6eba9a9ffc
Create Date: 2021-02-09 16:41:09.831657

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '546854af251f'
down_revision = 'ea6eba9a9ffc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel_metadata', sa.String(), nullable=True))
        batch_op.alter_column(
            'size',
            existing_type=sa.INTEGER(),
            type_=sa.BigInteger(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            'size_limit',
            existing_type=sa.INTEGER(),
            type_=sa.BigInteger(),
            existing_nullable=True,
        )

    with op.batch_alter_table('package_versions', schema=None) as batch_op:
        batch_op.alter_column(
            'size',
            existing_type=sa.INTEGER(),
            type_=sa.BigInteger(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package_versions', schema=None) as batch_op:
        batch_op.alter_column(
            'size',
            existing_type=sa.BigInteger(),
            type_=sa.INTEGER(),
            existing_nullable=True,
        )

    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.alter_column(
            'size_limit',
            existing_type=sa.BigInteger(),
            type_=sa.INTEGER(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            'size',
            existing_type=sa.BigInteger(),
            type_=sa.INTEGER(),
            existing_nullable=True,
        )
        batch_op.drop_column('channel_metadata')

    # ### end Alembic commands ###
