"""case insensitive channel names

Revision ID: a3ffa287d074
Revises: a80fb051a659
Create Date: 2020-12-07 14:10:27.374580

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a3ffa287d074'
down_revision = 'a80fb051a659'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_context().dialect == 'postgresql':
        op.execute(
            "CREATE COLLATION nocase (provider = icu, "
            "locale = 'und-u-ks-level2', "
            "deterministic = false)"
        )
    op.alter_column("channels", "name", type_=sa.types.VARCHAR(100, collation="nocase"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("channels", "name", type_=sa.types.VARCHAR(None, collation=None))
    if op.get_context().dialect == 'postgresql':
        op.execute("DROP COLLATION nocase;")
    # ### end Alembic commands ###
