"""add per channel TTL

Revision ID: beb2fc24c206
Revises: 303ff70c27fc
Create Date: 2021-01-07 17:56:46.554993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beb2fc24c206'
down_revision = '303ff70c27fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channel_mirrors', 'api_endpoint',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('channel_mirrors', 'metrics_endpoint',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('channels', sa.Column('ttl', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'ttl')
    op.alter_column('channel_mirrors', 'metrics_endpoint',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('channel_mirrors', 'api_endpoint',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
