"""create index for download count

Revision ID: de0b61e5c651
Revises: 0653794b6252
Create Date: 2021-01-27 14:33:21.316385

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'de0b61e5c651'
down_revision = '0653794b6252'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aggregated_metrics', schema=None) as batch_op:
        batch_op.create_index(
            'package_version_metric_index',
            ['channel_name', 'platform', 'filename', 'metric_name', 'period'],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aggregated_metrics', schema=None) as batch_op:
        batch_op.drop_index('package_version_metric_index')

    # ### end Alembic commands ###
