"""add_repo_signing_key

Revision ID: dadfc30be670
Revises:
Create Date: 2021-05-28 14:20:01.479359

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'dadfc30be670'
down_revision = None
branch_labels = ('quetz-content_trust',)
depends_on = 'quetz'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'repodata_signing_keys',
        sa.Column('id', sa.LargeBinary(length=16), nullable=False),
        sa.Column('private_key', sa.String(), nullable=True),
        sa.Column(
            'time_created',
            sa.Date(),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.Column('user_id', sa.LargeBinary(length=16), nullable=True),
        sa.Column('channel_name', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ['channel_name'],
            ['channels.name'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repodata_signing_keys')
    # ### end Alembic commands ###
